# Generated by Django 3.2.13 on 2023-10-15 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='cookbooks/')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('recipe_image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('cookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubapp.cookbook')),
            ],
        ),
    ]
